### ISSUE TITLE
Add search command

### ISSUE THREAD

**Issue by Resi23** [JEFF-Media-GbR/Spigot-InvUnloadPlus#13]
Die Auflistung der Sortierten Items im Chat klickbar machen das Speziell der Container per Laser angzeigt wird.

**Comment by mfnalex** [comment]
Feature request: add a search command that searches nearby chests for a specific item and then list the results like /unloadinfo.
Also should include a clickable text link next to each result that will show a laser and particles to highlight that particular chest.

**Comment by Resi23** [comment]
ts? :D

**Comment by mfnalex** [comment]
Morgen (bzw heute) irgendwann?
