### ISSUE TITLE
Feature Request - Config file to allow which container types can be unloaded into

### ISSUE THREAD

**Issue by joshburer** [JEFF-Media-GbR/Spigot-InvUnloadPlus#35]
I have enjoyed this plugin greatly, but I have noticed that I am unable to stop from unloading into droppers or dispensers. This is especially problematic with shears, buckets, flint & steel, etc. Instead of requiring all of my players to blacklist these once they find out it does this, I would appreciate the option to just disable unloading into certain containers.

**Comment by mfnalex** [comment]
Good idea, will be added!
