### ISSUE TITLE
Blacklist commands do not check if items are already in blacklist

### ISSUE THREAD

**Issue by rutzfutz** [JEFF-Media-GbR/Spigot-InvUnloadPlus#40]
When I use one of the following methods to add items to the blacklist, InvUnload does not check if the items are already in the blacklist, and therefore adds duplicates:
- `/blacklist add` with item in hand
- `/blacklist add <item>`
- `/blacklist add inventory`

My InvUnload version is 4.9.4 running on PaperMC build 484 (MC: 1.16.5).

**Comment by mfnalex** [comment]
Thanks for reporting this, I'll check it out

**Comment by mfnalex** [comment]
Fixed in 4.9.5 :) update is released

**Comment by rutzfutz** [comment]
Wow, I'm impressed. Thank you for the incredibly quick fix!

**Comment by mfnalex** [comment]
You're welcome, thanks for the report!
