### ISSUE TITLE
New message-could-not-unload-blacklist is displayed if non-blacklisted item is in the last inventory slot and no matching chests are nearby

### ISSUE THREAD

**Issue by rutzfutz** [JEFF-Media-GbR/Spigot-InvUnloadPlus#43]
Thanks again for adding the new `message-could-not-unload-blacklist` message.

However, the slight differences in your inventory enumeration code (<= instead of <) cause a minor bug: If I have a non-blacklisted item in my last inventory slot, and no matching chests for this item are nearby, I incorrectly get the message stating that all items in my inventory are blacklisted.

If I put the non-blacklisted item anywhere else but in the last slot, I correctly get the message `message-could-not-unload`.

**Comment by mfnalex** [comment]
oh shit. I will look into this again

**Comment by mfnalex** [comment]
fixed in 4.10.1 :)

**Comment by mfnalex** [comment]
sorry I forgot to remove a debug message, please directly use 4.10.2
