### ISSUE TITLE
Request Compatibility

### ISSUE THREAD

**Issue by rpendrick** [JEFF-Media-GbR/Spigot-InvUnloadPlus#44]
hiya mfnalex!  We spoke on spigot, and you asked that I create a ticket on github for you.  Let me quote the conversation we had regarding the plugin ItemsAdder (custom items):

|     It does work (BTW fastest reply from a dev ever)!! However, the custom items are vanilla mc items with textures on them, and 
| your plugin (awesome perk) for the custom items, uses the hidden vanilla mc name, so for example, I am putting away "Ruby 
| Ores" it will call them "NOTEBLOCK" as that is the underlying vanilla item.... You know what, can I disable the message that 
| names the items?, even that would work for me... maybe just a "Inventory Unloaded" message...

|| Oh I see. Can you open a ticket on my discord or github? I tend to forget things people write on spigot but I can definitely fix 
|| that 

Here is a link to the ItemsAdder API (if you are going that route - vs just option to disable names of items unloaded):
[API](https://lonedev.gitbook.io/itemsadder/api)

Thank you kindly for your efforts.

- waqe  (-:

**Comment by mfnalex** [comment]
Thanks, I will have a look at their API tomorrow, unfortunately I don't have time for that today :/

**Comment by rpendrick** [comment]
Are you the fastest dev ever?  THANK YOU I appreciate it -- sending donation.  (-:

**Comment by mfnalex** [comment]
Oh, thanks so much :) Well as I said, I don't have time for that today, so I am not thaat fast haha

**Comment by mfnalex** [comment]
I just think - just disabling the message will not really be helpful, will it? It would still mean that your ruby things get into chests that already contain noteblocks :/ I could just add a check if an item is named, and if so, only store it inside chests that contain items with the same name, how does that sound?

**Comment by rpendrick** [comment]
Yes, I much prefer you do the harder work, but not my place to ask you to work a lot ---- if you can do it the longer API route, that would be the best yes, thank you!!  (-:

**Comment by mfnalex** [comment]
I'll try to find time for that tomorrow :)

**Comment by mfnalex** [comment]
Do you know if ItemsAdder is in any public maven repo? The API doesn't mention on how to properly add the dependency :/

**Comment by mfnalex** [comment]
Ah, I found it: https://github.com/LoneDev6/API-ItemsAdder#-packages

**Comment by mfnalex** [comment]
I'll try to add support tomorrow or thursday, can't promise yet though. Feel free to reply again if you have the feeling that I forgot about it :)

**Comment by mfnalex** [comment]
Please try if everything works as expected in 4.12.0-SNAPSHOT :) -> https://repo.jeff-media.de/maven2/de/jeff_media/InvUnload/4.12.0-SNAPSHOT/InvUnload-4.12.0-20210414.141350-2.jar
