### ISSUE TITLE
Feature Request: Plotsquared and radius per group

### ISSUE THREAD

**Issue by Resi23** [JEFF-Media-GbR/Spigot-InvUnloadPlus#9]
Wie der Titel sschon sagt wollte ich fragen ob du den Max Radius per Gruppe konfigurierbar machen kannst natürlich am besten über eine config.yml was ich in meinem speziellem Fall nicht berücksichtigt habe.

PlayerUtils:

`	
static Integer getMaxRadiusPerGroup(Player p){
		if (p.hasPermission("group.inhaber")) {
			return 50;
		} else if (p.hasPermission("group.lord")) {
			return 30;
		} else if (p.hasPermission("group.legende")) {
			return 25;
		} else if (p.hasPermission("group.magier")) {
			return 20;
		} else if (p.hasPermission("group.ultra")) {
			return 15;
		} else if (p.hasPermission("group.vip")) {
			return 10;		
		} else {
			return main.maxChestRadius;
		}
	}
`

Desweiteren wäre es cool wenn du Plotsquared unterstützen könntest das man nicht in Kisten auf Nachbarplots entleert.

canPlayerUseChest:

`
	// Calls PlayerInteractEvent to see if access is blocked by 3rd party plugins
	static boolean canPlayerUseChest(Block block, Player player) {
		PlayerInteractEvent event = new PlayerInteractEvent(player,
				Action.RIGHT_CLICK_BLOCK, null, block, BlockFace.UP);
		Bukkit.getPluginManager().callEvent(event);
		if(event.useInteractedBlock() == Event.Result.DENY) {
			return false;
		}
		Plot plot = BukkitUtil.getLocation(block.getLocation()).getPlotAbs();
		if (plot == null) {
			return false;
		}
		if (!plot.isOwner(player.getUniqueId())) {
			return false;
		}
		return true;
	}
`
Mit dem Source der V2.0.2 Hat es bei mir gut funktioniert.Mit 3.0.0 hab ich teilweise Probleme das ich 3-4 Blocke vor dem Container stehen muss obwohl der Radius höher steht.

**Comment by mfnalex** [comment]
Gute Idee :) mach doch mal bitte einen PullRequest auf, der Code ist leider grottig formatiert.

Das mit den 3-4 Blöcken kann ich nicht nachvollziehen, das sollte natürlich nicht so sein. Ich seh mir das später mal an, arbeite gerade noch an einem ChestSort-Update

**Comment by mfnalex** [comment]
Für den "Radius per Group" wird es ein yaml-File geben, so dass jeder die Gruppen beliebig anpassen kann.

**Comment by mfnalex** [comment]
Werde ich beides einbauen und erweitern, Update sollte heute fertig werden.

**Comment by mfnalex** [comment]
Plotsquared hat kein maven Repo, oder? Hast du das selbst kompiliert bzw. nutzt du Gradle, oder einfach die .jar in den BuildPath aufgenommen?

**Comment by mfnalex** [comment]
Ich seh grad, die haben ein maven Repo, also alles gut.

**Comment by mfnalex** [comment]
Benutzt ihr noch PlotSquared 4? In der API von Version 5 sehe ich nichts von BukkitUtil.

**Comment by Resi23** [comment]
Ja wir nutzen aktuell noch die v4 und ja wir haben es selbst kompiliert. Die v5 habe ich mir noch nicht angesehen. Aber man sollte sich das auch selbst zusammensetzten (https://hastebin.com/idazivosel.cs bevor ich vom Bukkitutil wusste) können bzw ich denke das es in der V5 etwas ähnliches geben müsste.

**Comment by mfnalex** [comment]
Müsste jetzt beides eingebaut sein. Bitte probier es mal mit dieser Version: http://repo.jeff-media.de/maven2/de/jeff_media/InvUnload/4.1.0/InvUnload-4.1.0.jar

Gibt auch neue config-Optionen bzgl. PlotSquared sowie eine neue Datei groups.yml (bzw groups.example.yml die man dann umbenennen muss wenn man sie nutzen möchte).

Bitte sag mir ob das mit PlotSquared klappt (habe das Plugin nicht). Das mit den Gruppen sollte jedenfalls klappen :)

Nach Rückmeldung lad ich die neue Version dann ofiiziell hoch.

**Comment by mfnalex** [comment]
Das mit den Trusted-Leuten hab ich grad erst gesehen, wird auch noch eingebaut. Aber sollte nicht standardmäßig jeder Kisten außerhalb von Plots nutzen dürfen? Habe PlotSquared noch nie benutzt, aber ich denke, als Standard-Einstellung sollte man eigentlich nur dann keinen Zugriff haben, wenn man
1. in einem Plot ist
2. weder Trusted noch Owner ist
oder?

**Comment by Resi23** [comment]
> Das mit den Trusted-Leuten hab ich grad erst gesehen, wird auch noch eingebaut. Aber sollte nicht standardmäßig jeder Kisten außerhalb von Plots nutzen dürfen? Habe PlotSquared noch nie benutzt, aber ich denke, als Standard-Einstellung sollte man eigentlich nur dann keinen Zugriff haben, wenn man
> 
> 1. in einem Plot ist
> 2. weder Trusted noch Owner ist
>    oder?

Ja das ist soweit richtig. Ich werde die Version oben mal testen weis aber nicht ob ich das heute noch schaffe. Ich melde mich morgen spätestens mit Ergebnissen zurück.

**Comment by mfnalex** [comment]
Moment, ich hab sofort eine neue Version fertig^^

**Comment by mfnalex** [comment]
http://repo.jeff-media.de/maven2/de/jeff_media/InvUnload/4.1.0-SNAPSHOT1/InvUnload-4.1.0-SNAPSHOT1.jar

Neue Config Optionen:

```
##### PlotSquared #####
# When enabled, InvUnload will check if you are using PlotSquared.
# Players will then only be able to unload into chests that are
# in their own plots and in plots that match the settings below
use-plotsquared: true

# Allows players to unload into chests that are in foreign Plots if
# the players is a trusted member of that plot
plotsquared-allow-when-trusted: true

# Allows players to unload into chests that do not belong to any Plot
plotsquared-allow-outside-plots: true
```

**Comment by Resi23** [comment]
Servus, leider bekomme ich eine Fehlermeldung beim ausführen des Befehls.
https://hastebin.com/ojuxetecic.rb

**Comment by mfnalex** [comment]
Ich guck mir das morgen mal an, die v4 ist ja kostenlos.

**Comment by mfnalex** [comment]
Wie lautet der vollständige Klassenname von BukkitUtil, bzw. welches Package hast du importiert?

**Comment by mfnalex** [comment]
Gibt nirgendswo mehr Infos über die API von v4 ...

**Comment by mfnalex** [comment]
com.github.intellectualsites.plotsquared.bukkit.util.BukkitUtil?

**Comment by Resi23** [comment]
> com.github.intellectualsites.plotsquared.bukkit.util.BukkitUtil?

genau die war das

**Comment by Resi23** [comment]
Ich glaub da hat auch etwas mit den radius nicht hin.

groups.yml

```
# You can define custom default-radius and max-radius values for certain groups.
# Players will need the invunload.group.[groupname] permission.
# Note: You MUST rename this file to groups.yml if you wish to use it.

inhaber:
  default-chest-radius: 5
  max-chest-radius: 50
lord:
  default-chest-radius: 5
  max-chest-radius: 30
legende:
  default-chest-radius: 5
  max-chest-radius: 25
magier:
  default-chest-radius: 5
  max-chest-radius: 20
ultra:
  default-chest-radius: 5
  max-chest-radius: 15
vip:
  default-chest-radius: 5
  max-chest-radius: 10
premium:
  default-chest-radius: 5
  max-chest-radius: 5
```
![Title](https://cloud.seedcraft.net/s/MXX4T7Q7Fk4wfcR/preview)

**Comment by mfnalex** [comment]
Bitte hiermit nochmal probieren:
http://repo.jeff-media.de/maven2/de/jeff_media/InvUnload/4.1.0-SNAPSHOT2/InvUnload-4.1.0-SNAPSHOT2.jar

Das mit den Gruppen schau ich mir gleich an

**Comment by mfnalex** [comment]
Das mit den Gruppen kann ich bestätigen, es kommt 0 raus wenn man in gar keiner Gruppe ist. Den Fall hatte ich nich getestet, sorry.

**Comment by mfnalex** [comment]
3ada00f94b6f6018df5ceafa5121f0a97a355d53
Sollte mit PlotSquared 4 funktionieren und die Gruppen sind gefixt.

http://repo.jeff-media.de/maven2/de/jeff_media/InvUnload/4.1.0-SNAPSHOT3/InvUnload-4.1.0-SNAPSHOT3.jar

Ob das auch mit PlotSquared 5 klappt kann ich nicht testen, sollte aber eigentlich keinen Unterschied machen.

**Comment by Resi23** [comment]
zwecks Plotsquared scheint es jetzt zu funktionieren.
Bei den Gruppen habe ich gerade noch das Problem das der Spieler eigentlich einen max-chest-radius von 30 haben müsste. Im Chat steht aber nur 20.

![Title](https://cloud.seedcraft.net/apps/files_sharing/publicpreview/owNpAfLNA4S8BKk?x=1879&y=589&a=true&file=invunload2.PNG&scalingup=0)

Das angesprochene Problem mit der Reichweite habe ich unten skizziert. in die Shulker mit dem rote gekritzle sollten die Items rein gehen tun sie auch wenn ich 2 Blöcke entfernt stehe. stehe ich ein paar mehr Blöcke weg dann nicht und das sind weder 20 noch 30 Blöcke entfernung

![Title](https://cloud.seedcraft.net/apps/files_sharing/publicpreview/HZ2bL3EnPpfZmeS?x=1879&y=589&a=true&file=invunload.PNG&scalingup=0)

**Comment by Resi23** [comment]
Vermutlich weil du in der GroupUtils in Zeile 39 ind 52 
`f(!p.hasPermission("invunload.groups."+group)) continue;`
nach invunload.groups."+group und nicht nach invunload.group."+group suchst wie in der groups.example.yml angegeben.

**Comment by mfnalex** [comment]
Ja das stimmt natürlich, ist gefixt.

http://repo.jeff-media.de/maven2/de/jeff_media/InvUnload/4.1.0-SNAPSHOT4/InvUnload-4.1.0-SNAPSHOT4.jar

Dass mit der Shulkerbox kann ich dennoch nicht nachvollziehen. Bei mir klappt das jedes mal perfekt. Bist du sicher dass es an der Entfernung liegt?

**Comment by Resi23** [comment]
Radius und Gruppen funktionieren nun wie gewollt. Auf meinem Testserver habe ich auch keine Probleme mit der Entfernung. Dann muss das ja irgendwo bei mir liegen. Was mir nur noch aufgefallen ist. Er packt zwar keine Items in die Kisten auf fremden Plots sortiert sie aber wenn ich /chestsort aktiviert habe. Gehört hier eventuell nicht hin fand ich aber erwähnenswert.

**Comment by Resi23** [comment]
Jetzt habe ich das Problem auch auf meinem Testserver wenn zuviel Container im spiel sind habe ich das Gefühl. 
Hier mit ca 10 Blöcke Abstand 
![Titel](https://cloud.seedcraft.net/apps/files_sharing/publicpreview/qGgbBr5tyT8beM6?x=1879&y=589&a=true&file=javaw_0fsmwogvgl.png&scalingup=0)

Hier mit ca 5 Blöcke Abstand 
![Titel](https://cloud.seedcraft.net/apps/files_sharing/publicpreview/e59Rz5zKQcmy3pT?x=1879&y=589&a=true&file=javaw_NVLTtaxkoj.png&scalingup=0)

Hier fast direkt vond er Truhe 
![Titel](https://cloud.seedcraft.net/apps/files_sharing/publicpreview/rRrCcfM6XjKRqan?x=1879&y=589&a=true&file=javaw_RBERTVTv6j.png&scalingup=0)

**Comment by mfnalex** [comment]
Kannst du mir die Testwelt mal schicken/hochladen?

**Comment by Resi23** [comment]
Klar allerdings habs ich nichts anders gemacht also dort einen Haufen Fässer hinzustellen mit Worldedit. https://cloud.seedcraft.net/s/Ht4SpjGCzGaxsmK

**Comment by mfnalex** [comment]
Lass mich raten: du hast ein Anti-Cheat-Plugin, dass das InventoryOpenEvent cancelled wenn der Spieler zu weit weg ist?

Wenn ja kann ich das wahrscheinlich problemlos fixen.

**Comment by Resi23** [comment]
Ich glaube des Rätsel Lösung ist mein Anticheat. Ich habs jetzt mal auf dem testserver rausgenommen und jetzt geht es auch auf mehr Entfernung. Das Problem hatte ich mit der V2.0.2 nicht dort kam aber glaube ich auch noch eine andere Methode bei https://cloud.seedcraft.net/s/Ht4SpjGCzGaxsmK zum einsatz

**Comment by mfnalex** [comment]
Ha, habs vor 20 Sekunden erraten =D

welches Plugin benutzt du denn? Ich kann im Event die Location einfach auf die Location der Kiste setzen, das sollte das dann umgehen

**Comment by Resi23** [comment]
Ich nutze [Spartan](https://www.spigotmc.org/resources/spartan-advanced-anti-cheat-hack-blocker.25638/)

**Comment by mfnalex** [comment]
Ups, das kostet ja. Ich lad dir in 5 Minuten eine neue Testversion hoch, bitte damit nochmal testen

**Comment by Resi23** [comment]
Alles klar

**Comment by mfnalex** [comment]
Fuck. Das PlayerInteractEvent hat keine eigene Location. Dann bleibt mir nur übrig mal zu sehen was die Spartan API so hergibt.

**Comment by mfnalex** [comment]
Ok, ich glaub ich kann das Abbrechen des Events durch Spartan abbrechen. 10 Minuten

**Comment by mfnalex** [comment]
Verdammt, muss ja dann erst wieder checken ob Spartan überhaupt installiert ist und ob die Klasse überhaupt existiert^^

**Comment by mfnalex** [comment]
Bitte testen: http://repo.jeff-media.de/maven2/de/jeff_media/InvUnload/4.1.0-SNAPSHOT5/InvUnload-4.1.0-SNAPSHOT5.jar

**Comment by Resi23** [comment]
Jetzt bekomme ich die Meldung Konnte nichts abladen sogar wenn ich auf dem Container stehe. Keine Fehlermeldungen in der Console.

**Comment by mfnalex** [comment]
Wtf... Ich kann das leider nicht testen, da ich ja Spartan nicht gekauft hab, aber ich seh mir das nochmal an, moment

**Comment by mfnalex** [comment]
Ich glaube die von Spartan haben einfach ihre API Methode falsch benannt. Laut dieser "Dokumentation" https://pastebin.com/raw/PH63gHRg (mehr als das haben die als API Docs für die Klasse nicht), sollte ich mit e.setCancelled(true) ja das Abbrechen durch Spartan abbrechen können. Offenbar ist es aber genau anders herum...

Bitte hiermit probieren: http://repo.jeff-media.de/maven2/de/jeff_media/InvUnload/4.1.0-SNAPSHOT6/InvUnload-4.1.0-SNAPSHOT6.jar

Übrigens sorry dass wir so viele Versuche brauchen, aber es ist echt ne Qual fremde APIs zu nutzen ohne die Plugins selbst zu haben.

**Comment by mfnalex** [comment]
Falls du Discord hast, adde mich mal bitte: mfnalex#1908

**Comment by Resi23** [comment]
Anfrage ist raus

**Comment by mfnalex** [comment]
http://repo.jeff-media.de/maven2/de/jeff_media/InvUnload/4.1.0/InvUnload-4.1.0.jar

Endlich ^^
